LINKEDIN_URL="https://www.linkedin.com/in/javi-lazaro/"
GITHUB_URL="https://github.com/pichu2707"
YOUTUBE_URL="https://www.youtube.com/@JaviLazaro"
TWITCH_URL="https://www.twitch.tv/javilazaro1"
GMAIL_URL="mailto:hola@javilazaro.es"
